"""fix created_at server default

Revision ID: 49210c94c007
Revises: ee02ebf81a2e
Create Date: 2026-02-22 15:57:58.354939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49210c94c007'
down_revision: Union[str, Sequence[str], None] = 'ee02ebf81a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               server_default=None)
    # ### end Alembic commands ###
