"""added timestamps to users model

Revision ID: 5cb3a9dc1601
Revises: 5411bc5ac4a0
Create Date: 2026-02-15 16:26:52.084708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5cb3a9dc1601'
down_revision: Union[str, Sequence[str], None] = '5411bc5ac4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('blockReason', sa.String(), nullable=False))
    op.add_column('users', sa.Column('refreshToken', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'username')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'image')
    op.drop_column('users', 'refreshToken')
    op.drop_column('users', 'blockReason')
    op.drop_column('users', 'blocked')
    op.drop_column('users', 'active')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
