"""fix nullable

Revision ID: c8a6c269db87
Revises: 49210c94c007
Create Date: 2026-02-22 21:37:59.168054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a6c269db87'
down_revision: Union[str, Sequence[str], None] = '49210c94c007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'blockReason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'blockReason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
